package com.cloudgenshin.tv;

import android.os.Build;
import android.webkit.WebView;

public class CompatibilityInjector {

    private static final String COMPAT_JS =
            "(function() {"
            + "if (window.__cloudGenshinCompatInjected) return;"
            + "window.__cloudGenshinCompatInjected = true;"

            + "var origGetUserAgent = navigator.userAgent;"
            + "try {"
            + "Object.defineProperty(navigator, 'userAgent', {"
            + "get: function() { return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'; }"
            + "});"
            + "} catch(e) {}"

            + "try {"
            + "Object.defineProperty(navigator, 'platform', {"
            + "get: function() { return 'Win32'; }"
            + "});"
            + "} catch(e) {}"

            + "try {"
            + "Object.defineProperty(navigator, 'appVersion', {"
            + "get: function() { return '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'; }"
            + "});"
            + "} catch(e) {}"

            + "if (!window.Promise) {"
            + "window.Promise = function(executor) {"
            + "var self = this;"
            + "self.state = 'pending';"
            + "self.value = undefined;"
            + "self.callbacks = [];"
            + "function resolve(value) {"
            + "if (self.state !== 'pending') return;"
            + "self.state = 'fulfilled';"
            + "self.value = value;"
            + "setTimeout(function() {"
            + "self.callbacks.forEach(function(cb) { try { cb.onFulfilled(value); } catch(e) {} });"
            + "}, 0);"
            + "}"
            + "function reject(reason) {"
            + "if (self.state !== 'pending') return;"
            + "self.state = 'rejected';"
            + "self.value = reason;"
            + "setTimeout(function() {"
            + "self.callbacks.forEach(function(cb) { try { cb.onRejected(reason); } catch(e) {} });"
            + "}, 0);"
            + "}"
            + "try { executor(resolve, reject); } catch(e) { reject(e); }"
            + "};"
            + "window.Promise.prototype.then = function(onFulfilled, onRejected) {"
            + "var self = this;"
            + "return new Promise(function(resolve, reject) {"
            + "function handle() {"
            + "try {"
            + "if (self.state === 'fulfilled') {"
            + "var result = onFulfilled ? onFulfilled(self.value) : self.value;"
            + "resolve(result);"
            + "} else if (self.state === 'rejected') {"
            + "if (onRejected) { var r = onRejected(self.value); resolve(r); } else { reject(self.value); }"
            + "}"
            + "} catch(e) { reject(e); }"
            + "}"
            + "if (self.state === 'pending') {"
            + "self.callbacks.push({ onFulfilled: handle, onRejected: handle });"
            + "} else { setTimeout(handle, 0); }"
            + "});"
            + "};"
            + "window.Promise.prototype.catch = function(onRejected) {"
            + "return this.then(null, onRejected);"
            + "};"
            + "window.Promise.resolve = function(value) {"
            + "return new Promise(function(resolve) { resolve(value); });"
            + "};"
            + "window.Promise.reject = function(reason) {"
            + "return new Promise(function(resolve, reject) { reject(reason); });"
            + "};"
            + "window.Promise.all = function(promises) {"
            + "return new Promise(function(resolve, reject) {"
            + "var results = [];"
            + "var remaining = promises.length;"
            + "if (remaining === 0) { resolve([]); return; }"
            + "promises.forEach(function(p, i) {"
            + "Promise.resolve(p).then(function(v) {"
            + "results[i] = v;"
            + "remaining--;"
            + "if (remaining === 0) resolve(results);"
            + "}, reject);"
            + "});"
            + "});"
            + "};"
            + "}"

            + "if (!window.fetch) {"
            + "window.fetch = function(url, options) {"
            + "return new Promise(function(resolve, reject) {"
            + "var xhr = new XMLHttpRequest();"
            + "var method = (options && options.method) || 'GET';"
            + "xhr.open(method, url, true);"
            + "if (options && options.headers) {"
            + "for (var key in options.headers) {"
            + "xhr.setRequestHeader(key, options.headers[key]);"
            + "}"
            + "}"
            + "xhr.onload = function() {"
            + "resolve({"
            + "ok: xhr.status >= 200 && xhr.status < 300,"
            + "status: xhr.status,"
            + "statusText: xhr.statusText,"
            + "text: function() { return Promise.resolve(xhr.responseText); },"
            + "json: function() { return Promise.resolve(JSON.parse(xhr.responseText)); },"
            + "headers: { get: function(name) { return xhr.getResponseHeader(name); } }"
            + "});"
            + "};"
            + "xhr.onerror = function() { reject(new Error('Network error')); };"
            + "xhr.send((options && options.body) || null);"
            + "});"
            + "};"
            + "}"

            + "if (!window.requestAnimationFrame) {"
            + "window.requestAnimationFrame = function(cb) { return setTimeout(cb, 16); };"
            + "window.cancelAnimationFrame = function(id) { clearTimeout(id); };"
            + "}"

            + "if (!window.AudioContext && window.webkitAudioContext) {"
            + "window.AudioContext = window.webkitAudioContext;"
            + "}"

            + "if (!window.RTCPeerConnection) {"
            + "if (window.webkitRTCPeerConnection) {"
            + "window.RTCPeerConnection = window.webkitRTCPeerConnection;"
            + "}"
            + "}"
            + "if (!window.RTCSessionDescription && window.webkitRTCSessionDescription) {"
            + "window.RTCSessionDescription = window.webkitRTCSessionDescription;"
            + "}"
            + "if (!window.RTCIceCandidate && window.webkitRTCIceCandidate) {"
            + "window.RTCIceCandidate = window.webkitRTCIceCandidate;"
            + "}"

            + "if (window.RTCPeerConnection) {"
            + "var OrigPeerConnection = window.RTCPeerConnection;"
            + "var origCreateOffer = OrigPeerConnection.prototype.createOffer;"
            + "var origCreateAnswer = OrigPeerConnection.prototype.createAnswer;"
            + "OrigPeerConnection.prototype.createOffer = function() {"
            + "var self = this;"
            + "var args = arguments;"
            + "return new Promise(function(resolve, reject) {"
            + "try {"
            + "origCreateOffer.call(self, function(sdp) { resolve(sdp); }, function(err) { reject(err); }, args[0]);"
            + "} catch(e) { reject(e); }"
            + "});"
            + "};"
            + "OrigPeerConnection.prototype.createAnswer = function() {"
            + "var self = this;"
            + "var args = arguments;"
            + "return new Promise(function(resolve, reject) {"
            + "try {"
            + "origCreateAnswer.call(self, function(sdp) { resolve(sdp); }, function(err) { reject(err); }, args[0]);"
            + "} catch(e) { reject(e); }"
            + "});"
            + "};"
            + "var origSetLocal = OrigPeerConnection.prototype.setLocalDescription;"
            + "OrigPeerConnection.prototype.setLocalDescription = function(sdp) {"
            + "var self = this;"
            + "return new Promise(function(resolve, reject) {"
            + "try {"
            + "origSetLocal.call(self, sdp, function() { resolve(); }, function(err) { reject(err); });"
            + "} catch(e) { reject(e); }"
            + "});"
            + "};"
            + "var origSetRemote = OrigPeerConnection.prototype.setRemoteDescription;"
            + "OrigPeerConnection.prototype.setRemoteDescription = function(sdp) {"
            + "var self = this;"
            + "return new Promise(function(resolve, reject) {"
            + "try {"
            + "origSetRemote.call(self, sdp, function() { resolve(); }, function(err) { reject(err); });"
            + "} catch(e) { reject(e); }"
            + "});"
            + "};"
            + "var origAddIce = OrigPeerConnection.prototype.addIceCandidate;"
            + "OrigPeerConnection.prototype.addIceCandidate = function(candidate) {"
            + "var self = this;"
            + "return new Promise(function(resolve, reject) {"
            + "try {"
            + "origAddIce.call(self, candidate, function() { resolve(); }, function(err) { reject(err); });"
            + "} catch(e) { reject(e); }"
            + "});"
            + "};"
            + "}"

            + "if (!Object.assign) {"
            + "Object.assign = function(target) {"
            + "for (var i = 1; i < arguments.length; i++) {"
            + "var source = arguments[i];"
            + "if (source) {"
            + "for (var key in source) {"
            + "if (Object.prototype.hasOwnProperty.call(source, key)) {"
            + "target[key] = source[key];"
            + "}"
            + "}"
            + "}"
            + "}"
            + "return target;"
            + "};"
            + "}"

            + "if (!Array.prototype.find) {"
            + "Array.prototype.find = function(predicate) {"
            + "for (var i = 0; i < this.length; i++) {"
            + "if (predicate(this[i], i, this)) return this[i];"
            + "}"
            + "return undefined;"
            + "};"
            + "}"

            + "if (!Array.prototype.includes) {"
            + "Array.prototype.includes = function(searchElement) {"
            + "return this.indexOf(searchElement) !== -1;"
            + "};"
            + "}"

            + "if (!String.prototype.includes) {"
            + "String.prototype.includes = function(search) {"
            + "return this.indexOf(search) !== -1;"
            + "};"
            + "}"

            + "if (!String.prototype.startsWith) {"
            + "String.prototype.startsWith = function(search) {"
            + "return this.indexOf(search) === 0;"
            + "};"
            + "}"

            + "if (!String.prototype.endsWith) {"
            + "String.prototype.endsWith = function(search) {"
            + "return this.lastIndexOf(search) === this.length - search.length;"
            + "};"
            + "}"

            + "try {"
            + "var origConnection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;"
            + "if (!navigator.connection) {"
            + "navigator.connection = { effectiveType: '4g', downlink: 10, rtt: 50 };"
            + "}"
            + "} catch(e) {}"

            + "try {"
            + "if (!navigator.hardwareConcurrency) {"
            + "navigator.hardwareConcurrency = 4;"
            + "}"
            + "} catch(e) {}"

            + "try {"
            + "if (!navigator.deviceMemory) {"
            + "navigator.deviceMemory = 2;"
            + "}"
            + "} catch(e) {}"

            + "if (!window.screen.orientation) {"
            + "window.screen.orientation = { type: 'landscape-primary', angle: 0 };"
            + "}"

            + "(function() {"
            + "var videoCheckCount = 0;"
            + "function checkVideoElements() {"
            + "var videos = document.querySelectorAll('video');"
            + "for (var i = 0; i < videos.length; i++) {"
            + "(function(v) {"
            + "if (v.readyState >= 2 && v.paused) {"
            + "try { v.play(); } catch(e) {}"
            + "}"
            + "if (v.srcObject || v.src) {"
            + "v.setAttribute('playsinline', '');"
            + "v.setAttribute('webkit-playsinline', '');"
            + "v.style.objectFit = 'contain';"
            + "if (v.readyState >= 2 && !v.videoWidth && v.currentTime > 0) {"
            + "try { v.load(); v.play(); } catch(e) {}"
            + "}"
            + "}"
            + "})(videos[i]);"
            + "}"
            + "videoCheckCount++;"
            + "if (videoCheckCount < 60) {"
            + "setTimeout(checkVideoElements, 1000);"
            + "}"
            + "}"
            + "setTimeout(checkVideoElements, 2000);"
            + "})();"

            + "(function() {"
            + "if (!window.RTCPeerConnection) return;"
            + "var OrigPC = window.RTCPeerConnection;"
            + "var origSetRemote = OrigPC.prototype.setRemoteDescription;"
            + "OrigPC.prototype.setRemoteDescription = function(sdp) {"
            + "var self = this;"
            + "if (sdp && sdp.sdp) {"
            + "try {"
            + "if (sdp.sdp.indexOf('H264') === -1 && sdp.sdp.indexOf('h264') === -1) {"
            + "sdp.sdp = sdp.sdp.replace(/m=video (\\d+) UDP\\/TLS\\/RTP\\/SAVPF (\\d+)/g,"
            + "'m=video $1 UDP/TLS/RTP/SAVPF $2');"
            + "}"
            + "} catch(e) {}"
            + "}"
            + "return origSetRemote.call(this, sdp);"
            + "};"
            + "})();"

            + "var style = document.createElement('style');"
            + "style.textContent = 'body { margin:0; padding:0; overflow:hidden; }';"
            + "if (document.head) { document.head.appendChild(style); }"

            + "console.log('[CloudGenshin] Compatibility layer injected');})();";

    private final WebView webView;

    public CompatibilityInjector(WebView webView) {
        this.webView = webView;
    }

    public void inject() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            webView.evaluateJavascript(COMPAT_JS, null);
        } else {
            webView.loadUrl("javascript:" + COMPAT_JS);
        }
    }

    public String getInjectionScript() {
        return COMPAT_JS;
    }
}
